eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics