server:
  port: 8080 # The single entry point for the user/frontend

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Auto-detect services
          lower-case-service-id: true
      routes:
        - id: environment-service
          uri: lb://ENVIRONMENT-SERVICE # lb = Load Balancer (via Eureka)
          predicates:
            - Path=/api/v1/environment/**
        - id: control-service
          uri: lb://CONTROL-SERVICE
          predicates:
            - Path=/api/v1/control/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/